//
// DefaultAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class DefaultAPI {
    /**
     Get or poll latest home posts

     - parameter toId: (query) To which post ID should the server poll latest posts on home. If both to_id and from_id are present, to_id will take precedence. (optional)
     - parameter fromId: (query) From which post ID should the server fetch posts on home. If empty, the server will fetch the latest posts. (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getHome(toId: String? = nil, fromId: String? = nil, completion: @escaping ((_ data: [Post]?,_ error: Error?) -> Void)) {
        getHomeWithRequestBuilder(toId: toId, fromId: fromId).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get or poll latest home posts
     - GET /home
     - 

     - :
       - type: http
       - name: bearer
     - examples: [{contentType=application/json, example=[ {
  "comments" : [ {
    "deleted" : false,
    "comments" : [ {
      "deleted" : false,
      "id" : "a3137edb-e629-49ac-b1f1-3343fd97329c",
      "created_at_seconds" : 1.4658129805029452,
      "content" : "Hello, World!",
      "media_urls" : [ "https://pill-city.s3.us-west-2.amazonaws.com/avatars/kt-1646414449.png", "https://pill-city.s3.us-west-2.amazonaws.com/avatars/ika-1631578.png" ]
    }, {
      "deleted" : false,
      "id" : "a3137edb-e629-49ac-b1f1-3343fd97329c",
      "created_at_seconds" : 1.4658129805029452,
      "content" : "Hello, World!",
      "media_urls" : [ "https://pill-city.s3.us-west-2.amazonaws.com/avatars/kt-1646414449.png", "https://pill-city.s3.us-west-2.amazonaws.com/avatars/ika-1631578.png" ]
    } ],
    "id" : "a3137edb-e629-49ac-b1f1-3343fd97329c",
    "created_at_seconds" : 6.027456183070403,
    "content" : "Hello, World!",
    "media_urls" : [ "https://pill-city.s3.us-west-2.amazonaws.com/avatars/kt-1646414449.png", "https://pill-city.s3.us-west-2.amazonaws.com/avatars/ika-1631578.png" ]
  }, {
    "deleted" : false,
    "comments" : [ {
      "deleted" : false,
      "id" : "a3137edb-e629-49ac-b1f1-3343fd97329c",
      "created_at_seconds" : 1.4658129805029452,
      "content" : "Hello, World!",
      "media_urls" : [ "https://pill-city.s3.us-west-2.amazonaws.com/avatars/kt-1646414449.png", "https://pill-city.s3.us-west-2.amazonaws.com/avatars/ika-1631578.png" ]
    }, {
      "deleted" : false,
      "id" : "a3137edb-e629-49ac-b1f1-3343fd97329c",
      "created_at_seconds" : 1.4658129805029452,
      "content" : "Hello, World!",
      "media_urls" : [ "https://pill-city.s3.us-west-2.amazonaws.com/avatars/kt-1646414449.png", "https://pill-city.s3.us-west-2.amazonaws.com/avatars/ika-1631578.png" ]
    } ],
    "id" : "a3137edb-e629-49ac-b1f1-3343fd97329c",
    "created_at_seconds" : 6.027456183070403,
    "content" : "Hello, World!",
    "media_urls" : [ "https://pill-city.s3.us-west-2.amazonaws.com/avatars/kt-1646414449.png", "https://pill-city.s3.us-west-2.amazonaws.com/avatars/ika-1631578.png" ]
  } ],
  "author" : {
    "avatar_url" : "https://pill-city.s3.us-west-2.amazonaws.com/avatars/kt-1646414449.png",
    "profile_pic" : "pill1.png",
    "id" : "kt",
    "created_at_seconds" : 1631528113,
    "display_name" : "KT 一號機"
  },
  "is_update_avatar" : false,
  "circles" : [ {
    "name" : "圈子",
    "id" : "a3137edb-e629-49ac-b1f1-3343fd97329c"
  }, {
    "name" : "圈子",
    "id" : "a3137edb-e629-49ac-b1f1-3343fd97329c"
  } ],
  "reshared_from" : "",
  "poll" : "",
  "created_at_seconds" : 0.8008281904610115,
  "reshareable" : true,
  "content" : "Hello, World!",
  "deleted" : false,
  "is_public" : true,
  "reactions" : [ {
    "emoji" : "💩",
    "id" : "a3137edb-e629-49ac-b1f1-3343fd97329c"
  }, {
    "emoji" : "💩",
    "id" : "a3137edb-e629-49ac-b1f1-3343fd97329c"
  } ],
  "id" : "a3137edb-e629-49ac-b1f1-3343fd97329c",
  "media_urls" : [ "https://pill-city.s3.us-west-2.amazonaws.com/avatars/kt-1646414449.png", "https://pill-city.s3.us-west-2.amazonaws.com/avatars/ika-1631578.png" ]
}, {
  "comments" : [ {
    "deleted" : false,
    "comments" : [ {
      "deleted" : false,
      "id" : "a3137edb-e629-49ac-b1f1-3343fd97329c",
      "created_at_seconds" : 1.4658129805029452,
      "content" : "Hello, World!",
      "media_urls" : [ "https://pill-city.s3.us-west-2.amazonaws.com/avatars/kt-1646414449.png", "https://pill-city.s3.us-west-2.amazonaws.com/avatars/ika-1631578.png" ]
    }, {
      "deleted" : false,
      "id" : "a3137edb-e629-49ac-b1f1-3343fd97329c",
      "created_at_seconds" : 1.4658129805029452,
      "content" : "Hello, World!",
      "media_urls" : [ "https://pill-city.s3.us-west-2.amazonaws.com/avatars/kt-1646414449.png", "https://pill-city.s3.us-west-2.amazonaws.com/avatars/ika-1631578.png" ]
    } ],
    "id" : "a3137edb-e629-49ac-b1f1-3343fd97329c",
    "created_at_seconds" : 6.027456183070403,
    "content" : "Hello, World!",
    "media_urls" : [ "https://pill-city.s3.us-west-2.amazonaws.com/avatars/kt-1646414449.png", "https://pill-city.s3.us-west-2.amazonaws.com/avatars/ika-1631578.png" ]
  }, {
    "deleted" : false,
    "comments" : [ {
      "deleted" : false,
      "id" : "a3137edb-e629-49ac-b1f1-3343fd97329c",
      "created_at_seconds" : 1.4658129805029452,
      "content" : "Hello, World!",
      "media_urls" : [ "https://pill-city.s3.us-west-2.amazonaws.com/avatars/kt-1646414449.png", "https://pill-city.s3.us-west-2.amazonaws.com/avatars/ika-1631578.png" ]
    }, {
      "deleted" : false,
      "id" : "a3137edb-e629-49ac-b1f1-3343fd97329c",
      "created_at_seconds" : 1.4658129805029452,
      "content" : "Hello, World!",
      "media_urls" : [ "https://pill-city.s3.us-west-2.amazonaws.com/avatars/kt-1646414449.png", "https://pill-city.s3.us-west-2.amazonaws.com/avatars/ika-1631578.png" ]
    } ],
    "id" : "a3137edb-e629-49ac-b1f1-3343fd97329c",
    "created_at_seconds" : 6.027456183070403,
    "content" : "Hello, World!",
    "media_urls" : [ "https://pill-city.s3.us-west-2.amazonaws.com/avatars/kt-1646414449.png", "https://pill-city.s3.us-west-2.amazonaws.com/avatars/ika-1631578.png" ]
  } ],
  "author" : {
    "avatar_url" : "https://pill-city.s3.us-west-2.amazonaws.com/avatars/kt-1646414449.png",
    "profile_pic" : "pill1.png",
    "id" : "kt",
    "created_at_seconds" : 1631528113,
    "display_name" : "KT 一號機"
  },
  "is_update_avatar" : false,
  "circles" : [ {
    "name" : "圈子",
    "id" : "a3137edb-e629-49ac-b1f1-3343fd97329c"
  }, {
    "name" : "圈子",
    "id" : "a3137edb-e629-49ac-b1f1-3343fd97329c"
  } ],
  "reshared_from" : "",
  "poll" : "",
  "created_at_seconds" : 0.8008281904610115,
  "reshareable" : true,
  "content" : "Hello, World!",
  "deleted" : false,
  "is_public" : true,
  "reactions" : [ {
    "emoji" : "💩",
    "id" : "a3137edb-e629-49ac-b1f1-3343fd97329c"
  }, {
    "emoji" : "💩",
    "id" : "a3137edb-e629-49ac-b1f1-3343fd97329c"
  } ],
  "id" : "a3137edb-e629-49ac-b1f1-3343fd97329c",
  "media_urls" : [ "https://pill-city.s3.us-west-2.amazonaws.com/avatars/kt-1646414449.png", "https://pill-city.s3.us-west-2.amazonaws.com/avatars/ika-1631578.png" ]
} ]}]
     - parameter toId: (query) To which post ID should the server poll latest posts on home. If both to_id and from_id are present, to_id will take precedence. (optional)
     - parameter fromId: (query) From which post ID should the server fetch posts on home. If empty, the server will fetch the latest posts. (optional)

     - returns: RequestBuilder<[Post]> 
     */
    open class func getHomeWithRequestBuilder(toId: String? = nil, fromId: String? = nil) -> RequestBuilder<[Post]> {
        let path = "/home"
        let URLString = PillCityAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "to_id": toId, 
                        "from_id": fromId
        ])


        let requestBuilder: RequestBuilder<[Post]>.Type = PillCityAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**
     Get the loggined in user

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getMe(completion: @escaping ((_ data: User?,_ error: Error?) -> Void)) {
        getMeWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get the loggined in user
     - GET /me
     - 

     - :
       - type: http
       - name: bearer
     - examples: [{contentType=application/json, example={
  "avatar_url" : "https://pill-city.s3.us-west-2.amazonaws.com/avatars/kt-1646414449.png",
  "profile_pic" : "pill1.png",
  "id" : "kt",
  "created_at_seconds" : 1631528113,
  "display_name" : "KT 一號機"
}}]

     - returns: RequestBuilder<User> 
     */
    open class func getMeWithRequestBuilder() -> RequestBuilder<User> {
        let path = "/me"
        let URLString = PillCityAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<User>.Type = PillCityAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**
     Sign in

     - parameter body: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func signIn(body: Any? = nil, completion: @escaping ((_ data: InlineResponse200?,_ error: Error?) -> Void)) {
        signInWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Sign in
     - POST /signIn
     - 

     - examples: [{contentType=application/json, example={
  "access_token" : "xyz.123",
  "expires" : 1652301806
}}]
     - parameter body: (body)  (optional)

     - returns: RequestBuilder<InlineResponse200> 
     */
    open class func signInWithRequestBuilder(body: Any? = nil) -> RequestBuilder<InlineResponse200> {
        let path = "/signIn"
        let URLString = PillCityAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<InlineResponse200>.Type = PillCityAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
}
