//
// AllOfPostResharedFrom.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AllOfPostResharedFrom: Codable {

    /** Permanent ID for the reshared post */
    public var _id: String
    /** In epoch seconds, when the reshared post was created */
    public var createdAtSeconds: Decimal
    public var author: User
    /** Text content for the reshared post */
    public var content: String?
    /** URLs for the reshared post&#x27;s media */
    public var mediaUrls: [String]?
    /** Whether the reshared post is deleted */
    public var deleted: Bool?

    public init(_id: String, createdAtSeconds: Decimal, author: User, content: String? = nil, mediaUrls: [String]? = nil, deleted: Bool? = nil) {
        self._id = _id
        self.createdAtSeconds = createdAtSeconds
        self.author = author
        self.content = content
        self.mediaUrls = mediaUrls
        self.deleted = deleted
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case createdAtSeconds = "created_at_seconds"
        case author
        case content
        case mediaUrls = "media_urls"
        case deleted
    }

}
