//
// Circle.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Circle: Codable {

    /** Permanent ID for the circle */
    public var _id: String
    /** Circle name */
    public var name: String

    public init(_id: String, name: String) {
        self._id = _id
        self.name = name
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
    }

}
