//
// CloudEmoticonCategory.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CloudEmoticonCategory: Codable {

    /** The category name */
    public var name: String
    /** Emoticon entries for the category */
    public var entries: [CloudEmoticonEntry]

    public init(name: String, entries: [CloudEmoticonEntry]) {
        self.name = name
        self.entries = entries
    }


}
