//
// CloudEmoticonEntry.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CloudEmoticonEntry: Codable {

    /** The emoticon */
    public var emoticon: String
    /** Description for the emoticon */
    public var _description: String

    public init(emoticon: String, _description: String) {
        self.emoticon = emoticon
        self._description = _description
    }

    public enum CodingKeys: String, CodingKey { 
        case emoticon
        case _description = "description"
    }

}
