//
// CloudEmoticonRepo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CloudEmoticonRepo: Codable {

    /** Emoticon categories for the repo */
    public var categories: [CloudEmoticonCategory]
    /** Description for the repo */
    public var information: [String]

    public init(categories: [CloudEmoticonCategory], information: [String]) {
        self.categories = categories
        self.information = information
    }


}
