//
// InlineResponse200.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse200: Codable {

    /** User&#x27;s bearer token */
    public var accessToken: String
    /** In epoch seconds, when the bearer token will expire */
    public var expires: Decimal

    public init(accessToken: String, expires: Decimal) {
        self.accessToken = accessToken
        self.expires = expires
    }

    public enum CodingKeys: String, CodingKey { 
        case accessToken = "access_token"
        case expires
    }

}
