//
// MediaUrlV2.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MediaUrlV2: Codable {

    /** Original URL to the media */
    public var originalUrl: String
    /** Whether the media has been processed/optimized */
    public var processed: Bool
    /** Processed media width */
    public var width: Decimal?
    /** Processed media height */
    public var height: Decimal?
    /** Processed media dominant color in hex */
    public var dominantColorHex: String?

    public init(originalUrl: String, processed: Bool, width: Decimal? = nil, height: Decimal? = nil, dominantColorHex: String? = nil) {
        self.originalUrl = originalUrl
        self.processed = processed
        self.width = width
        self.height = height
        self.dominantColorHex = dominantColorHex
    }

    public enum CodingKeys: String, CodingKey { 
        case originalUrl = "original_url"
        case processed
        case width
        case height
        case dominantColorHex = "dominant_color_hex"
    }

}
