//
// Message.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Message: Codable {

    /** This is a message */
    public var msg: String

    public init(msg: String) {
        self.msg = msg
    }


}
