//
// Poll.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Poll: Codable {

    /** Choices for this poll */
    public var choices: [PollChoice]?
    /** In epoch seconds, by when this poll will close. Default 0 meaning the poll will never close. */
    public var closeBySeconds: Decimal?

    public init(choices: [PollChoice]? = nil, closeBySeconds: Decimal? = nil) {
        self.choices = choices
        self.closeBySeconds = closeBySeconds
    }

    public enum CodingKeys: String, CodingKey { 
        case choices
        case closeBySeconds = "close_by_seconds"
    }

}
