//
// PollChoice.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PollChoice: Codable {

    /** Permanent ID for the poll choice */
    public var _id: String
    /** Text content for the poll choice */
    public var content: String
    /** URL for the poll choice&#x27;s media */
    public var media: String
    public var mediaUrlV2: MediaUrlV2?
    /** User who have voted for this poll choice */
    public var voters: [User]?

    public init(_id: String, content: String, media: String, mediaUrlV2: MediaUrlV2? = nil, voters: [User]? = nil) {
        self._id = _id
        self.content = content
        self.media = media
        self.mediaUrlV2 = mediaUrlV2
        self.voters = voters
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case content
        case media
        case mediaUrlV2 = "media_url_v2"
        case voters
    }

}
