//
// Reaction.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Reaction: Codable {

    /** Permanent ID for the reaction */
    public var _id: String
    /** Emoji for the reaction */
    public var emoji: String
    public var author: User

    public init(_id: String, emoji: String, author: User) {
        self._id = _id
        self.emoji = emoji
        self.author = author
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case emoji
        case author
    }

}
